
const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
const CLEAR_SEARCH_RESULT = 'CEAR_SEARCH_RESULT';
const UPDATE_MAP_PLACES = 'UPDATE_MAP_PLACES';
const ADD_MARKER = 'ADD_MARKER';
const REMOVE_MARKER = 'REMOVE_MARKER';

const UPDATE_DIRECTION = 'UPDATE_DIRECTION';
const CLEAR_DIRECTION = 'CLEAR_DIRECTION';

const UPDATE_USER = 'UPDATE_USER';
const DELETE_USER = 'DELETE_USER';

export {UPDATE_SEARCH_RESULT, CLEAR_SEARCH_RESULT, UPDATE_MAP_PLACES, ADD_MARKER, REMOVE_MARKER, UPDATE_DIRECTION, CLEAR_DIRECTION,
    UPDATE_USER, DELETE_USER};